[package]
name = "chord-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bitflags = "2.9.0"
enigo = "0.3.0"
serde = "1.0.219"
serde_json = "1.0.140"
serial2 = "0.2.28"

[target.x86_64-unknown-linux-gnu]
linker = "nix-ld"

